/**
 * Central registry of application error codes.
 *
 * Every typed error thrown by application services must use one of these
 * codes so API responses stay consistent (see shared/errors/app-error.ts)
 * and so clients can branch on `error.code` instead of parsing messages.
 */
export const ErrorCode = {
  // Generic / cross-cutting
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  FORBIDDEN: "FORBIDDEN",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  IDEMPOTENCY_KEY_REUSED: "IDEMPOTENCY_KEY_REUSED",
  INTERNAL_ERROR: "INTERNAL_ERROR",

  // Auth
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_ALREADY_REGISTERED: "EMAIL_ALREADY_REGISTERED",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  INVALID_TOKEN: "INVALID_TOKEN",

  // Organizations
  ORGANIZATION_NOT_VERIFIED: "ORGANIZATION_NOT_VERIFIED",
  ORGANIZATION_SUSPENDED: "ORGANIZATION_SUSPENDED",

  // Documents
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",

  // Sender IDs
  SENDER_ID_NOT_ACTIVE: "SENDER_ID_NOT_ACTIVE",
  SENDER_ID_INVALID_TRANSITION: "SENDER_ID_INVALID_TRANSITION",

  // Messaging
  INVALID_RECIPIENT: "INVALID_RECIPIENT",
  MESSAGE_REJECTED: "MESSAGE_REJECTED",
  MESSAGE_NOT_CANCELLABLE: "MESSAGE_NOT_CANCELLABLE",

  // Wallet / billing
  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
  PAYMENT_FAILED: "PAYMENT_FAILED",

  // Provider
  PROVIDER_UNAVAILABLE: "PROVIDER_UNAVAILABLE",
  PROVIDER_CIRCUIT_OPEN: "PROVIDER_CIRCUIT_OPEN",

  // Fraud
  FRAUD_REVIEW_REQUIRED: "FRAUD_REVIEW_REQUIRED",

  // API keys
  API_KEY_INVALID: "API_KEY_INVALID",
  API_KEY_REVOKED: "API_KEY_REVOKED",
  API_KEY_ENVIRONMENT_MISMATCH: "API_KEY_ENVIRONMENT_MISMATCH",
  API_KEY_SCOPE_INSUFFICIENT: "API_KEY_SCOPE_INSUFFICIENT",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
